### ISSUE TITLE
XSUB_TYPE=torqueでjob statusが "E" の場合の例外処理

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/xsub#14]
# 症状
- XSUB_TYPE=torque のとき，ジョブステータスがEになる場合がある．
- ステータスEはxsubでサポートされていないのでraiseが呼ばれ例外が発生する
- status= :unknownが返されないのでジョブディレクトリのダウンロードが行われない

# エラーログ
```
Xsub is failed. 
#<RemoteJobHandler::RemoteSchedulerError: remote_status failed: rc:1, XSUB_BEGIN
, /home/uchitane/git/xsub/lib/xsub/schedulers/torque.rb:55:in `status': unknown output: Job id                    Name             User            Time Use S Queue (RuntimeError)
------------------------- ---------------- --------------- -------- - -----
352056.desrt4-01           ...e0800_xsub.sh uchitane        01:42:44 E batch          
	from /home/uchitane/git/xsub/lib/xsub/runner.rb:70:in `run'
	from /home/uchitane/git/xsub/bin/xstat:10:in `<main>'
>
["/home/oacis/oacis/app/services/remote_job_handler.rb:36:in `block in remote_status'", "/home/oacis/oacis/app/models/host.rb:125:in `start_ssh'", "/home/oacis/oacis/app/services/remote_job_handler.rb:30:in `remote_status'", "/home/oacis/oacis/app/workers/job_observer.rb:46:in `observe_job'", "/home/oacis/oacis/app/workers/job_observer.rb:28:in `block (2 levels) in observe_host'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual/mongo.rb:648:in `yield_document'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual/mongo.rb:123:in `block in each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/cursor.rb:28:in `block in each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/cursor.rb:28:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/cursor.rb:28:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/query.rb:77:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual/mongo.rb:122:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual.rb:20:in `each'", "/home/oacis/oacis/app/workers/job_observer.rb:26:in `block in observe_host'", "/home/oacis/oacis/app/models/host.rb:130:in `block in start_ssh'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/net-ssh-2.8.0/lib/net/ssh.rb:208:in `start'", "/home/oacis/oacis/app/models/host.rb:127:in `start_ssh'", "/home/oacis/oacis/app/workers/job_observer.rb:23:in `observe_host'", "/home/oacis/oacis/app/workers/job_observer.rb:10:in `block in perform'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual/mongo.rb:648:in `yield_document'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual/mongo.rb:123:in `block in each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/cursor.rb:28:in `block in each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/cursor.rb:28:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/cursor.rb:28:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/moped-2.0.3/lib/moped/query.rb:77:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual/mongo.rb:122:in `each'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.1/lib/mongoid/contextual.rb:20:in `each'", "/home/oacis/oacis/app/workers/job_observer.rb:5:in `perform'", "/home/oacis/oacis/app/workers/job_observer_worker.rb:10:in `block in <class:JobObserverWorker>'", "/home/oacis/oacis/app/workers/worker.rb:24:in `call'", "/home/oacis/oacis/app/workers/worker.rb:24:in `block (2 levels) in start'", "/home/oacis/oacis/app/workers/worker.rb:23:in `each'", "/home/oacis/oacis/app/workers/worker.rb:23:in `block in start'", "/home/oacis/oacis/app/workers/worker.rb:22:in `loop'", "/home/oacis/oacis/app/workers/worker.rb:22:in `start'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:51:in `block in start'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:38:in `fork'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:38:in `start'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:181:in `block in start'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:181:in `map'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:181:in `start'", "/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:165:in `spawn!'", "/home/oacis/oacis/lib/tasks/boot_job_observer_worker.rb:2:in `<main>'"]
```

# 対策
- ステータスEなど登録されていないジョブ状態の場合にはstatus= :unknownを返し，エラーを出さない
- job_observerで受け取れる[:submitted, :running, :includable, :unknown]以外のステータスをxsubが返さないようにする

**Comment by yohm** [comment]
qstatのmanによれば、E  - Job is exiting after having run. とあるので、:runningを返すようにする。
